/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.giv.pesados;

/**
 *
 * @author willi
 */
public class FrmUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmUsuarios
     */
    
    // Variable para guardar el ID del usuario al que le demos clic en la tabla
    private int idSeleccionado = 0;
    
    
    public FrmUsuarios() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDui = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setText("REGISTRO DE USUARIOS");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("DUI:");

        jLabel4.setText("Teléfono:");

        jLabel5.setText("Correo Electrónico:");

        jLabel6.setText("Nombre de Usuario:");

        jLabel7.setText("Contraseña:");

        jLabel8.setText("Rol de Acceso:");

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedor" }));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setText("Eliminar");

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(557, 557, 557)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(104, 104, 104)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                                    .addComponent(txtApellido)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDui)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtCorreo)
                                    .addComponent(txtUsuario)
                                    .addComponent(txtClave, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(45, 45, 45)
                                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(472, 472, 472)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
// 1. EXTRAER TODOS LOS DATOS
        String nombre = txtNombre.getText().trim(); // El trim() elimina espacios al inicio y final
        String apellido = txtApellido.getText().trim();
        String dui = txtDui.getText().trim();
        String telefono = txtTelefono.getText().trim();
        String correo = txtCorreo.getText().trim();
        String usuario = txtUsuario.getText().trim();
        String clavePlana = new String(txtClave.getPassword()).trim();
        String rolSeleccionado = cmbRol.getSelectedItem().toString();

        // 2. VALIDACIÓN NIVEL 1: CAMPOS VACÍOS
        if (nombre.isEmpty() || apellido.isEmpty() || dui.isEmpty() || 
            telefono.isEmpty() || correo.isEmpty() || usuario.isEmpty() || clavePlana.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Todos los campos son obligatorios. No se permiten campos vacíos.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Detener ejecución
        }

        // 3. VALIDACIÓN NIVEL 2: FORMATOS CORRECTOS (Expresiones Regulares)
        // Validar que nombre y apellido solo tengan letras (y espacios entre nombres)
        if (!nombre.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$") || !apellido.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: El nombre y apellido solo pueden contener letras.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar formato del DUI (8 números, guion, 1 número)
        if (!dui.matches("^\\d{8}-\\d{1}$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: El formato del DUI debe ser 00000000-0.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar correo (que tenga @ y un punto)
        if (!correo.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingrese un correo electrónico válido.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 4. PREPARAR DATOS FINALES
        // Convertir el texto del ComboBox al número que espera la Base de Datos
        int idRol = rolSeleccionado.equals("Administrador") ? 1 : 2;
        // Encriptar la contraseña usando tu clase de seguridad
        String claveEncriptada = Seguridad.encriptarSHA256(clavePlana);

        // 5. ENVIAR A LA BASE DE DATOS (Google Cloud)
        try {
            java.sql.Connection cn = Conexion.getInstancia().conectar();
            
            // Primero, verificar que el nombre_usuario no exista ya (Validación de duplicados)
            String sqlCheck = "SELECT nombre_usuario FROM USUARIOS WHERE nombre_usuario = ?";
            java.sql.PreparedStatement pstCheck = cn.prepareStatement(sqlCheck);
            pstCheck.setString(1, usuario);
            java.sql.ResultSet rs = pstCheck.executeQuery();
            
            if (rs.next()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: El nombre de usuario '" + usuario + "' ya existe. Elija otro.", "Duplicado", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Si pasa todas las pruebas, Insertar
            String sqlInsert = "INSERT INTO USUARIOS (nombre, apellido, nombre_usuario, DUI, correo, telefono, estado, clave, rol) VALUES (?, ?, ?, ?, ?, ?, 1, ?, ?)";
            java.sql.PreparedStatement pst = cn.prepareStatement(sqlInsert);
            
            pst.setString(1, nombre);
            pst.setString(2, apellido);
            pst.setString(3, usuario);
            pst.setString(4, dui);
            pst.setString(5, correo);
            pst.setString(6, telefono);
            pst.setString(7, claveEncriptada);
            pst.setInt(8, idRol);

            pst.executeUpdate(); // Ejecutar guardado
            
            javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario Registrado Exitosamente en la Nube!");
            
            // TODO: Aquí llamaremos al método para limpiar las cajas de texto y actualizar la tabla
            
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error de Base de Datos: " + e.getMessage(), "Error Crítico", javax.swing.JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        
// 1. Averiguar a qué fila se le dio clic
        int filaSeleccionada = tblUsuarios.getSelectedRow();

        if (filaSeleccionada >= 0) {
            // 2. Guardar el ID de la columna 0 en nuestra variable secreta
            idSeleccionado = Integer.parseInt(tblUsuarios.getValueAt(filaSeleccionada, 0).toString());

            // 3. Subir los datos a las cajitas
            txtNombre.setText(tblUsuarios.getValueAt(filaSeleccionada, 1).toString());
            txtApellido.setText(tblUsuarios.getValueAt(filaSeleccionada, 2).toString());
            txtUsuario.setText(tblUsuarios.getValueAt(filaSeleccionada, 3).toString());
            txtDui.setText(tblUsuarios.getValueAt(filaSeleccionada, 4).toString());
            
            // Seleccionar el rol correcto en la lista desplegable
            String rol = tblUsuarios.getValueAt(filaSeleccionada, 5).toString();
            cmbRol.setSelectedItem(rol);
            
            // La contraseña la dejamos vacía por seguridad
            txtClave.setText("");
            
            // Bloqueamos la caja de usuario para que no le cambien el "username" al actualizar
            txtUsuario.setEditable(false);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
txtUsuario.setEditable(true);
// Vaciar todas las cajitas
        txtNombre.setText("");
        txtApellido.setText("");
        txtDui.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtUsuario.setText("");
        txtClave.setText("");
        cmbRol.setSelectedIndex(0); 
        
        // Desbloquear la caja de usuario por si queremos guardar uno nuevo
        txtUsuario.setEnabled(true);
        
        // Resetear el ID
        idSeleccionado = 0;

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        

// 1. Validar que se haya seleccionado un usuario en la tabla
        if (idSeleccionado == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un usuario de la tabla primero.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Extraer datos (El usuario no se extrae porque no se puede cambiar)
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String dui = txtDui.getText().trim();
        String telefono = txtTelefono.getText().trim();
        String correo = txtCorreo.getText().trim();
        String clavePlana = new String(txtClave.getPassword()).trim();
        int idRol = cmbRol.getSelectedItem().toString().equals("Administrador") ? 1 : 2;

        // 3. Validaciones de campos vacíos y formatos
        if (nombre.isEmpty() || apellido.isEmpty() || dui.isEmpty() || telefono.isEmpty() || correo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los datos personales son obligatorios.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!dui.matches("^\\d{8}-\\d{1}$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El formato del DUI debe ser 00000000-0.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 4. Actualizar en Google Cloud
        try {
            java.sql.Connection cn = Conexion.getInstancia().conectar();
            java.sql.PreparedStatement pst;

            // Lógica: ¿Escribió una nueva contraseña o la dejó en blanco?
            if (clavePlana.isEmpty()) {
                // Actualizar todo MENOS la contraseña
                String sql = "UPDATE USUARIOS SET nombre=?, apellido=?, DUI=?, telefono=?, correo=?, rol=? WHERE id_usuario=?";
                pst = cn.prepareStatement(sql);
                pst.setString(1, nombre);
                pst.setString(2, apellido);
                pst.setString(3, dui);
                pst.setString(4, telefono);
                pst.setString(5, correo);
                pst.setInt(6, idRol);
                pst.setInt(7, idSeleccionado);
            } else {
                // Encriptar la nueva y actualizar TODO
                String claveEncriptada = Seguridad.encriptarSHA256(clavePlana);
                String sql = "UPDATE USUARIOS SET nombre=?, apellido=?, DUI=?, telefono=?, correo=?, rol=?, clave=? WHERE id_usuario=?";
                pst = cn.prepareStatement(sql);
                pst.setString(1, nombre);
                pst.setString(2, apellido);
                pst.setString(3, dui);
                pst.setString(4, telefono);
                pst.setString(5, correo);
                pst.setInt(6, idRol);
                pst.setString(7, claveEncriptada);
                pst.setInt(8, idSeleccionado);
            }

            pst.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario actualizado correctamente!");
            
            // Refrescar la tabla para ver los cambios
            cargarTabla();
            
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }


// TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDui;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables






// Método para mostrar los usuarios en la tabla
    private void cargarTabla() {
        // 1. Configurar los títulos de las columnas
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Usuario");
        modelo.addColumn("DUI");
        modelo.addColumn("Rol");
        
        tblUsuarios.setModel(modelo);

        // 2. Traer los datos de Google Cloud
        try {
            java.sql.Connection cn = Conexion.getInstancia().conectar();
            // Solo traemos a los usuarios activos (estado = 1)
            String sql = "SELECT id_usuario, nombre, apellido, nombre_usuario, DUI, rol FROM USUARIOS WHERE estado = 1";
            java.sql.Statement st = cn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            // 3. Llenar la tabla fila por fila
            String[] fila = new String[6];
            while (rs.next()) {
                fila[0] = rs.getString("id_usuario");
                fila[1] = rs.getString("nombre");
                fila[2] = rs.getString("apellido");
                fila[3] = rs.getString("nombre_usuario");
                fila[4] = rs.getString("DUI");
                
                // Convertir el número de rol a texto para que sea entendible
                int rolDB = rs.getInt("rol");
                fila[5] = (rolDB == 1) ? "Administrador" : "Vendedor";
                
                modelo.addRow(fila);
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar la tabla: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }



}
