/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.giv.pesados.vistas;

import com.mycompany.giv.pesados.dao.CategoriaDAO;
import com.mycompany.giv.pesados.modelos.Categoria;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author uto
 */
public class FrmCategorias extends javax.swing.JInternalFrame {
    private CategoriaDAO categoriaDAO;
    private int idCategoriaSeleccionada = 0;
    /**
     * Creates new form FrmCategorias
     */
    private void cargarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Categoría");
        modelo.addColumn("Descripción");

        List<Categoria> lista = categoriaDAO.listarCategoriasActivas();
        Object[] fila = new Object[3];
        
        for (Categoria c : lista) {
            fila[0] = c.getIdCategoria();
            fila[1] = c.getNombreCategoria();
            fila[2] = c.getDescripcion();
            modelo.addRow(fila);
        }
        
        tblCategorias.setModel(modelo);
    }
    public FrmCategorias() {
        initComponents();
        categoriaDAO = new CategoriaDAO();
        cargarTabla();
    }
    private void limpiarCampos() {
        txtNombreCategoria.setText("");
        txaDescripcion.setText("");
        idCategoriaSeleccionada = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        txtNombreCategoria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txaDescripcion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategorias = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        panel1.setBackground(new java.awt.Color(204, 204, 204));
        panel1.setPreferredSize(new java.awt.Dimension(600, 500));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel1.add(txtNombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 140, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre categoria:");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Descripcion:");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        panel1.add(txaDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        panel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        panel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        btnLimpiar.setText("limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        panel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCategorias);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 580, 260));

        btnActualizar.setText("Editar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);
        panel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombreCategoria.getText().trim();
        String descripcion = txaDescripcion.getText().trim();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre de la categoría es obligatorio.", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Categoria cat = new Categoria();
        cat.setNombreCategoria(nombre);
        cat.setDescripcion(descripcion);

        if (categoriaDAO.registrarCategoria(cat)) {
            JOptionPane.showMessageDialog(this, "Categoría guardada exitosamente.");
            limpiarCampos();
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar la categoría.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (idCategoriaSeleccionada == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una categoría de la tabla para eliminar.", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar esta categoría?", "Confirmar", JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            if (categoriaDAO.eliminarCategoria(idCategoriaSeleccionada)) {
                JOptionPane.showMessageDialog(this, "Categoría eliminada (baja lógica) exitosamente.");
                limpiarCampos();
                cargarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoriasMouseClicked
        // TODO add your handling code here:
        int fila = tblCategorias.getSelectedRow();
        if (fila >= 0) {
            idCategoriaSeleccionada = Integer.parseInt(tblCategorias.getValueAt(fila, 0).toString());
            txtNombreCategoria.setText(tblCategorias.getValueAt(fila, 1).toString());
            txaDescripcion.setText(tblCategorias.getValueAt(fila, 2).toString());
        }
    }//GEN-LAST:event_tblCategoriasMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        // 1. Validar que haya tocado un registro en la tabla primero
        if (idCategoriaSeleccionada == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una categoría de la tabla para editar.", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Extraer el texto
        String nombre = txtNombreCategoria.getText().trim();
        String descripcion = txaDescripcion.getText().trim();

        // 3. Validar que no esté vacío
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre de la categoría es obligatorio.", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 4. Empaquetar en el DTO
        Categoria cat = new Categoria();
        cat.setIdCategoria(idCategoriaSeleccionada); // Pasamos el ID oculto
        cat.setNombreCategoria(nombre);
        cat.setDescripcion(descripcion);

        // 5. Enviar al DAO
        if (categoriaDAO.actualizarCategoria(cat)) {
            JOptionPane.showMessageDialog(this, "Categoría actualizada exitosamente.");
            limpiarCampos();
            cargarTabla(); // Refresca la tabla para ver el cambio
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar la categoría.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel1;
    private javax.swing.JTable tblCategorias;
    private javax.swing.JTextField txaDescripcion;
    private javax.swing.JTextField txtNombreCategoria;
    // End of variables declaration//GEN-END:variables
}
