/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.giv.pesados.vistas;

import com.mycompany.giv.pesados.config.Conexion;
import com.mycompany.giv.pesados.config.Seguridad;

/**
 *
 * @author willi
 */
public class FrmLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        
        // 1. Ajustar el Logo (Asegúrate de que la ruta sea correcta)
        ajustarImagen(LbLogo, "/GIV-PESADOS.png");
        
        // 2. Ajustar el Fondo (Sobrescribe la imagen que pone NetBeans para que encaje perfecto)
        ajustarImagen(LbFondo, "/fondo.jpg");
        
        
    }
    /**
     * Método auxiliar para ajustar cualquier imagen al tamaño de un JLabel
     */
  private void ajustarImagen(javax.swing.JLabel label, String ruta) {
    System.out.println("--- Intentando cargar: " + ruta + " ---");
    try {
        java.net.URL url = getClass().getResource(ruta);
        if (url != null) {
            System.out.println("1. ¡Imagen ENCONTRADA en la carpeta resources!");
            javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(url);
            
            int ancho = label.getWidth();
            int alto = label.getHeight();
            System.out.println("2. Tamaño inicial - Ancho: " + ancho + ", Alto: " + alto);
            
            if (ancho == 0 || alto == 0) {
                ancho = label.getPreferredSize().width;
                alto = label.getPreferredSize().height;
                System.out.println("3. Usando tamaño de diseño (PreferredSize) - Ancho: " + ancho + ", Alto: " + alto);
            }
            
            if (ancho > 0 && alto > 0) {
                java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_SMOOTH);
                label.setIcon(new javax.swing.ImageIcon(imagenEscalada));
                System.out.println("4. ¡Imagen ESCALADA y ASIGNADA al JLabel con éxito!");
            } else {
                System.out.println("ERROR: El tamaño del JLabel sigue siendo 0. La imagen no se puede dibujar.");
            }
        } else {
            System.out.println("ERROR FATAL: Java no encuentra el archivo en esa ruta.");
        }
    } catch (Exception e) {
        System.out.println("Excepción detectada: " + e.getMessage());
    }
    System.out.println("----------------------------------------");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        LbLogo = new javax.swing.JLabel();
        LbFondo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("GIV - PESADOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 298, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        txtClave.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 298, -1));

        btnIngresar.setBackground(new java.awt.Color(42, 157, 143));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.setOpaque(true);
        btnIngresar.addActionListener(this::btnIngresarActionPerformed);
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 147, 58));

        LbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 360, 280));

        LbFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(LbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 320, 500));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Inicio de Sesión");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Santa Ana");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        // 1. Obtener los datos de las cajitas de texto
        String usuario = txtUsuario.getText();
        String clave = new String(txtClave.getPassword());
        
        String claveEncriptada = Seguridad.encriptarSHA256(clave);
        

        // 2. Validar que no estén vacíos
        if (usuario.isEmpty() || clave.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Detiene la ejecución aquí
        }

        // 3. Consultar a la Base de Datos
        try {
            java.sql.Connection cn = Conexion.getInstancia().conectar();
            // Buscamos al usuario que coincida y que esté activo (estado = 1)
            String sql = "SELECT * FROM USUARIOS WHERE nombre_usuario = ? AND clave = ? AND estado = 1";
            
            java.sql.PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, usuario);
            pst.setString(2, claveEncriptada);

            java.sql.ResultSet rs = pst.executeQuery();

            // 4. Evaluar el resultado
            if (rs.next()) {
                // Si rs.next() es true, significa que encontró al usuario
                int rol = rs.getInt("rol");
                String nombre = rs.getString("nombre");
                
                javax.swing.JOptionPane.showMessageDialog(this, "¡Bienvenido al sistema, " + nombre + "!\nTu rol es: " + (rol == 1 ? "Administrador" : "Vendedor"));
                
                
                
                

// 1. Cerrar y destruir la ventana del Login
                this.dispose();
                
                // 2. Crear el MDI pasándole el número de rol que vino de la base de datos
               
                MdiPrincipal mdi = new MdiPrincipal(rol);
                
                // 3. Mostrar el MDI gigante
                mdi.setVisible(true);
                
                
                
                
                
                
            } else {
                // Si es false, las credenciales no coinciden
                javax.swing.JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Error de Acceso", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al conectar con el servidor: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbFondo;
    private javax.swing.JLabel LbLogo;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
