/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.giv.pesados.vistas;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.mycompany.giv.pesados.dao.CategoriaDAO;
import com.mycompany.giv.pesados.dao.ProductoDAO;
import com.mycompany.giv.pesados.modelos.Categoria;
import com.mycompany.giv.pesados.modelos.Producto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author uto
 */
public class FrmProductos extends javax.swing.JInternalFrame {
    private ProductoDAO productoDAO;
    private CategoriaDAO categoriaDAO;
    private int idProductoSeleccionado = 0;
    private DefaultTableModel modeloTabla;
    private TableRowSorter<DefaultTableModel> sorter;

    /**
     * Creates new form FrmProductos
     */
    public FrmProductos() {
        initComponents();
        productoDAO = new ProductoDAO();
        categoriaDAO = new CategoriaDAO();
        
        cargarCategorias();
        cargarTabla();
    }
    
    private void mostrarImagen(String ruta) {
        if (ruta != null && !ruta.trim().isEmpty()) {
            File archivo = new File(ruta);
            if (archivo.exists()) {
                ImageIcon iconoOriginal = new ImageIcon(ruta);
                // Ajustamos la imagen al ancho y alto del lblImage
                Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
                lblImage.setIcon(new ImageIcon(imagenEscalada));
                return; // Si todo salió bien, cortamos la ejecución aquí
            } 
        }
        
        // Si la ruta está vacía, es nula o el archivo no existe, cargamos el default
        java.net.URL imgUrl = getClass().getResource("/img/default.jpg");
        if (imgUrl != null) {
            ImageIcon iconoDefault = new ImageIcon(imgUrl);
            Image imagenEscalada = iconoDefault.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
            lblImage.setIcon(new ImageIcon(imagenEscalada));
        } else {
            lblImage.setIcon(null);
        }
    }
    
    private void cargarCategorias() {
        DefaultListModel<Categoria> modeloLista = new DefaultListModel<>();
        List<Categoria> categorias = categoriaDAO.listarCategoriasActivas();
        
        for (Categoria c : categorias) {
            modeloLista.addElement(c);
        }
        lstCategorias.setModel(modeloLista);
    }
    ///cargar tabla
    ///
    private void cargarTabla() {
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Repuesto");
        modeloTabla.addColumn("N° Serie");
        modeloTabla.addColumn("Marca");
        modeloTabla.addColumn("Precio ($)");
        modeloTabla.addColumn("Stock");
        modeloTabla.addColumn("Mínimo"); // 
        modeloTabla.addColumn("Ruta Imagen"); // Columna 7
        modeloTabla.addColumn("Descripción"); // Columna 8 (Nueva)
        
        List<Producto> lista = productoDAO.listarProductosActivos();
        Object[] fila = new Object[9];
        
        for (Producto p : lista) {
            fila[0] = p.getIdProducto();
            fila[1] = p.getNombreRepuesto();
            fila[2] = p.getNumSerie();
            fila[3] = p.getMarca();
            fila[4] = p.getPrecioVenta();
            fila[5] = p.getStockActual();
            fila[6] = p.getStockMinimo();
            fila[7] = p.getRutaImagen();
            fila[8] = p.getDescripcion();
            modeloTabla.addRow(fila);
        }
        
        tblProductos.setModel(modeloTabla);
        
        // Inicializar el motor de búsqueda en memoria
        sorter = new TableRowSorter<>(modeloTabla);
        tblProductos.setRowSorter(sorter);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumSerie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStockActual = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtStockMinimo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCategorias = new javax.swing.JList<>();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaDescripcion = new javax.swing.JTextArea();
        txtNombreRepuesto = new javax.swing.JTextField();
        txtImage = new javax.swing.JTextField();
        btnSeleccion = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        panel2.setBackground(new java.awt.Color(204, 204, 204));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Buscar:");
        panel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        panel2.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 190, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre del Repuesto:");
        panel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Número de serie:");
        panel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        panel2.add(txtNumSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 170, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("marca:");
        panel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        panel2.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 100, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Descripción:");
        panel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Imagen:");
        panel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));
        panel2.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 90, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Stock actual:");
        panel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));
        panel2.add(txtStockActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 90, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Stock mínimo:");
        panel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, 20));
        panel2.add(txtStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 90, -1));

        jScrollPane1.setViewportView(lstCategorias);

        panel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 170, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        panel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);
        panel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        panel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        btnLimpiar.setText("limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        panel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProductos);

        panel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 810, 220));

        txaDescripcion.setColumns(20);
        txaDescripcion.setRows(5);
        jScrollPane3.setViewportView(txaDescripcion);

        panel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 190, 90));
        panel2.add(txtNombreRepuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 170, -1));
        panel2.add(txtImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 150, -1));

        btnSeleccion.setText("Seleccionar...");
        btnSeleccion.addActionListener(this::btnSeleccionActionPerformed);
        panel2.add(btnSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Precio venta:");
        panel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        lblImage.setForeground(new java.awt.Color(0, 0, 0));
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/default.jpg"))); // NOI18N
        panel2.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 260, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (!validarCampos()) return; // Si la validación falla, detenemos la ejecución

        Producto p = crearProductoDesdeFormulario();
        List<Integer> idCategorias = obtenerCategoriasSeleccionadas();

        if (productoDAO.registrarProductoConCategorias(p, idCategorias)) {
            JOptionPane.showMessageDialog(this, "¡Repuesto registrado exitosamente en el inventario!");
            limpiarCampos();
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el repuesto.", "Error de BD", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        if (idProductoSeleccionado == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un repuesto de la tabla para actualizar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!validarCampos()) return;

        Producto p = crearProductoDesdeFormulario();
        p.setIdProducto(idProductoSeleccionado); // Asignamos el ID oculto
        List<Integer> idCategorias = obtenerCategoriasSeleccionadas();

        if (productoDAO.actualizarProductoConCategorias(p, idCategorias)) {
            JOptionPane.showMessageDialog(this, "Inventario actualizado correctamente.");
            limpiarCampos();
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar el repuesto.", "Error de BD", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (idProductoSeleccionado == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un repuesto para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de dar de baja este repuesto del inventario?", "Confirmar Baja", JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            if (productoDAO.eliminarProducto(idProductoSeleccionado)) {
                JOptionPane.showMessageDialog(this, "Repuesto eliminado del sistema.");
                limpiarCampos();
                cargarTabla();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        int filaVista = tblProductos.getSelectedRow();
        if (filaVista >= 0) {
            int filaModelo = tblProductos.convertRowIndexToModel(filaVista);
            
            // 1. Extraer los datos básicos
            idProductoSeleccionado = Integer.parseInt(modeloTabla.getValueAt(filaModelo, 0).toString());
            txtNombreRepuesto.setText(modeloTabla.getValueAt(filaModelo, 1) != null ? modeloTabla.getValueAt(filaModelo, 1).toString() : "");
            txtNumSerie.setText(modeloTabla.getValueAt(filaModelo, 2) != null ? modeloTabla.getValueAt(filaModelo, 2).toString() : "");
            txtMarca.setText(modeloTabla.getValueAt(filaModelo, 3) != null ? modeloTabla.getValueAt(filaModelo, 3).toString() : "");
            txtPrecioVenta.setText(modeloTabla.getValueAt(filaModelo, 4) != null ? modeloTabla.getValueAt(filaModelo, 4).toString() : "");
            txtStockActual.setText(modeloTabla.getValueAt(filaModelo, 5) != null ? modeloTabla.getValueAt(filaModelo, 5).toString() : "");
            txtStockMinimo.setText(modeloTabla.getValueAt(filaModelo, 6) != null ? modeloTabla.getValueAt(filaModelo, 6).toString() : "");
            
            // 2. Extraer Imagen y Descripción (Las columnas que agregamos)
            String rutaImg = modeloTabla.getValueAt(filaModelo, 7) != null ? modeloTabla.getValueAt(filaModelo, 7).toString() : "";
            txtImage.setText(rutaImg);
            mostrarImagen(rutaImg); // Llama a tu método mágico
            
            String descripcion = modeloTabla.getValueAt(filaModelo, 8) != null ? modeloTabla.getValueAt(filaModelo, 8).toString() : "";
            txaDescripcion.setText(descripcion);

            // 3. Seleccionar las categorías en el JList
            List<Integer> idsCategorias = categoriaDAO.obtenerIdCategoriasPorProducto(idProductoSeleccionado);
            List<Integer> indicesSeleccionados = new ArrayList<>();
            
            // Recorremos el modelo visual del JList para ver cuáles coinciden con la BD
            for (int i = 0; i < lstCategorias.getModel().getSize(); i++) {
                Categoria cat = lstCategorias.getModel().getElementAt(i);
                if (idsCategorias.contains(cat.getIdCategoria())) {
                    indicesSeleccionados.add(i);
                }
            }
            
            // Convertimos la lista de Integer a un int[] porque así lo pide Java Swing
            int[] arrIndices = indicesSeleccionados.stream().mapToInt(i -> i).toArray();
            lstCategorias.setSelectedIndices(arrIndices);
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        String textoFiltro = txtBuscar.getText().trim();
        // Filtramos buscando en todas las columnas (magia pura de Java Swing)
        if (textoFiltro.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            // (?i) hace que la búsqueda ignore mayúsculas y minúsculas
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + textoFiltro)); 
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar Imagen del Repuesto");
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imágenes (JPG, PNG, GIF)", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(filtro);

        int respuesta = fileChooser.showOpenDialog(this);
        if (respuesta == JFileChooser.APPROVE_OPTION) {
            String rutaSeleccionada = fileChooser.getSelectedFile().getAbsolutePath();
            txtImage.setText(rutaSeleccionada);
            mostrarImagen(rutaSeleccionada);
        }
    }//GEN-LAST:event_btnSeleccionActionPerformed

private void limpiarCampos() {
        txtNombreRepuesto.setText("");
        txtNumSerie.setText("");
        txtMarca.setText("");
        txaDescripcion.setText("");
        txtPrecioVenta.setText("");
        txtStockActual.setText("");
        txtStockMinimo.setText("");
        txtBuscar.setText("");
        lstCategorias.clearSelection();
        idProductoSeleccionado = 0;
        txtImage.setText("");
        java.net.URL imgUrl = getClass().getResource("/img/default.jpg");
        if (imgUrl != null) {
            ImageIcon iconoDefault = new ImageIcon(imgUrl);
            Image imagenEscalada = iconoDefault.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
            lblImage.setIcon(new ImageIcon(imagenEscalada));
        } else {
            lblImage.setIcon(null);
        }
        
        if(sorter != null) sorter.setRowFilter(null); // Quitar filtro
    }
private Producto crearProductoDesdeFormulario() {
        Producto p = new Producto();
        p.setNombreRepuesto(txtNombreRepuesto.getText().trim());
        p.setNumSerie(txtNumSerie.getText().trim());
        p.setMarca(txtMarca.getText().trim());
        p.setDescripcion(txaDescripcion.getText().trim());
        p.setPrecioVenta(Float.parseFloat(txtPrecioVenta.getText().trim()));
        p.setStockActual(Integer.parseInt(txtStockActual.getText().trim()));
        p.setStockMinimo(Integer.parseInt(txtStockMinimo.getText().trim()));
        p.setRutaImagen(txtImage.getText().trim());
        return p;
    }
private List<Integer> obtenerCategoriasSeleccionadas() {
        List<Categoria> seleccionadas = lstCategorias.getSelectedValuesList();
        List<Integer> ids = new ArrayList<>();
        for (Categoria c : seleccionadas) {
            ids.add(c.getIdCategoria());
        }
        return ids;
    }
private boolean validarCampos() {
        if (txtImage.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una imagen para el repuesto.", "Validación", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (txtNombreRepuesto.getText().trim().isEmpty() || txtPrecioVenta.getText().trim().isEmpty() || 
            txtStockActual.getText().trim().isEmpty() || txtStockMinimo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, llene los campos obligatorios (Nombre, Precio y Stocks).", "Validación", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        try {
            Float.parseFloat(txtPrecioVenta.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio de venta debe ser un número válido (ej: 150.50).", "Validación Numérica", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        try {
            Integer.parseInt(txtStockActual.getText().trim());
            Integer.parseInt(txtStockMinimo.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Las cantidades de stock deben ser números enteros sin decimales.", "Validación Numérica", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (lstCategorias.getSelectedValuesList().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe clasificar el repuesto en al menos una categoría de la lista.", "Validación", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSeleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblImage;
    private javax.swing.JList<Categoria> lstCategorias;
    private javax.swing.JPanel panel2;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextArea txaDescripcion;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtImage;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombreRepuesto;
    private javax.swing.JTextField txtNumSerie;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtStockActual;
    private javax.swing.JTextField txtStockMinimo;
    // End of variables declaration//GEN-END:variables
}
