/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.giv.pesados.vistas;

import com.mycompany.giv.pesados.config.Conexion;
import com.mycompany.giv.pesados.config.Seguridad;
import com.mycompany.giv.pesados.dao.UsuarioDAO;
import com.mycompany.giv.pesados.modelos.Usuario;

/**
 *
 * @author willi
 */
public class FrmUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmUsuarios
     */
    
    // Variable para guardar el ID del usuario al que le demos clic en la tabla
    private int idSeleccionado = 0;
    
    
    public FrmUsuarios() {
        initComponents();
        this.setSize(1050, 750);

        Usuario usuarioVacio = new Usuario(); // Crea un usuario con todos los strings nulos/vacios
        cargarTabla(usuarioVacio);
        
        
        
        // === ESTILO DE LA TABLA (DISEÑO HTML) ===
        // 1. Diseño del encabezado (Azul Marino con letras blancas)
        tblUsuarios.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        tblUsuarios.getTableHeader().setOpaque(false);
        tblUsuarios.getTableHeader().setBackground(new java.awt.Color(0, 52, 89));
        tblUsuarios.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        
        // 2. Diseño de las filas (Letra Segoe UI y filas más altas)
        tblUsuarios.setRowHeight(30); 
        tblUsuarios.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        
        // 3. Color al hacer clic en una fila (Azul Celeste)
        tblUsuarios.setSelectionBackground(new java.awt.Color(0, 180, 216));
        tblUsuarios.setSelectionForeground(java.awt.Color.WHITE);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDui = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombres:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 3, true));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 290, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Apellidos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        txtApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 3, true));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 290, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DUI:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        txtDui.setBackground(new java.awt.Color(255, 255, 255));
        txtDui.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDui.setForeground(new java.awt.Color(0, 0, 0));
        txtDui.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 3, true));
        jPanel1.add(txtDui, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Teléfono:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 3, true));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 160, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Correo Electrónico:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, 39));

        txtCorreo.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 3, true));
        txtCorreo.addActionListener(this::txtCorreoActionPerformed);
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 230, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Usuario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 3, true));
        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 150, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Contraseña:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));

        txtClave.setBackground(new java.awt.Color(255, 255, 255));
        txtClave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtClave.setForeground(new java.awt.Color(0, 0, 0));
        txtClave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 3, true));
        jPanel1.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 160, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Rol de Acceso:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        cmbRol.setBackground(new java.awt.Color(255, 255, 255));
        cmbRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbRol.setForeground(new java.awt.Color(0, 0, 0));
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedor" }));
        cmbRol.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 3, true));
        jPanel1.add(cmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 238, -1));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 880, 190));

        btnLimpiar.setBackground(new java.awt.Color(153, 204, 255));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 100, -1));

        btnGuardar.setBackground(new java.awt.Color(153, 204, 255));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 100, -1));

        btnActualizar.setBackground(new java.awt.Color(153, 204, 255));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 100, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("REGISTRO DE USUARIOS️");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(lblTitulo)
                .addContainerGap(393, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 100));

        btnBuscar.setBackground(new java.awt.Color(0, 102, 255));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        
// 1. Averiguar a qué fila se le dio clic
        int filaSeleccionada = tblUsuarios.getSelectedRow();

        if (filaSeleccionada >= 0) {
            // 2. Guardar el ID de la columna 0 en nuestra variable secreta
            idSeleccionado = Integer.parseInt(tblUsuarios.getValueAt(filaSeleccionada, 0).toString());

            // 3. Subir los datos a las cajitas respetando el nuevo orden
            txtNombre.setText(tblUsuarios.getValueAt(filaSeleccionada, 1).toString());
            txtApellido.setText(tblUsuarios.getValueAt(filaSeleccionada, 2).toString());
            txtUsuario.setText(tblUsuarios.getValueAt(filaSeleccionada, 3).toString());
            txtDui.setText(tblUsuarios.getValueAt(filaSeleccionada, 4).toString());
            txtCorreo.setText(tblUsuarios.getValueAt(filaSeleccionada, 5).toString());   // <--- CORREO ARREGLADO
            txtTelefono.setText(tblUsuarios.getValueAt(filaSeleccionada, 6).toString()); // <--- TELÉFONO ARREGLADO
            
            // Seleccionar el rol correcto en la lista desplegable (ahora pasó a la columna 7)
            String rol = tblUsuarios.getValueAt(filaSeleccionada, 7).toString();
            cmbRol.setSelectedItem(rol);
            
            // La contraseña la dejamos vacía por seguridad
            txtClave.setText("");
            
            // Blindaje 100%: Bloqueamos la edición para que no cambien el "username"
            //txtUsuario.setEditable(false);
        }
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String dui = txtDui.getText().trim();
        String telefono = txtTelefono.getText().trim();
        String correo = txtCorreo.getText().trim();
        String usuarioStr = txtUsuario.getText().trim();
        String clavePlana = new String(txtClave.getPassword()).trim();
        String rolSeleccionado = cmbRol.getSelectedItem().toString();

        if (nombre.isEmpty() || apellido.isEmpty() || dui.isEmpty() || telefono.isEmpty() || correo.isEmpty() || usuarioStr.isEmpty() || clavePlana.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validaciones RegEx
        if (!nombre.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$") || !apellido.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El nombre y apellido solo pueden contener letras.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!dui.matches("^\\d{8}-\\d{1}$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El formato del DUI debe ser 00000000-0.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!telefono.matches("^\\d{8}$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El teléfono debe tener exactamente 8 números seguidos.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!correo.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un correo electrónico válido.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        UsuarioDAO dao = new UsuarioDAO();
        if (dao.existeUsuario(usuarioStr)) {
            javax.swing.JOptionPane.showMessageDialog(this, "El nombre de usuario '" + usuarioStr + "' ya existe.", "Duplicado", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        Usuario u = new Usuario();
        u.setNombre(nombre);
        u.setApellido(apellido);
        u.setNombreUsuario(usuarioStr);
        u.setDui(dui);
        u.setTelefono(telefono);
        u.setCorreo(correo);
        u.setRol(rolSeleccionado.equals("Administrador") ? 1 : 2);
        u.setClave(Seguridad.encriptarSHA256(clavePlana));

        if (dao.registrarUsuario(u)) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario Registrado Exitosamente!");
            btnLimpiar.doClick();
            Usuario usuarioVacio = new Usuario(); // Crea un usuario con todos los strings nulos/vacios
            cargarTabla(usuarioVacio);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el usuario.", "Error de BD", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (idSeleccionado == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione el usuario que desea eliminar.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
                "¿Está seguro que desea dar de baja a este usuario?", "Confirmar Eliminación", 
                javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            UsuarioDAO dao = new UsuarioDAO();
            if (dao.eliminarUsuario(idSeleccionado)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Usuario dado de baja exitosamente.");
                btnLimpiar.doClick();
                Usuario usuarioVacio = new Usuario(); // Crea un usuario con todos los strings nulos/vacios
                cargarTabla(usuarioVacio);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar el usuario.", "Error de BD", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        
        txtNombre.setText("");
        txtApellido.setText("");
        txtDui.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtUsuario.setText("");
        txtClave.setText("");
        cmbRol.setSelectedIndex(0); 
        
        txtUsuario.setEditable(true);
        idSeleccionado = 0;
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        if (idSeleccionado == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un usuario de la tabla primero.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String dui = txtDui.getText().trim();
        String telefono = txtTelefono.getText().trim();
        String correo = txtCorreo.getText().trim();
        String clavePlana = new String(txtClave.getPassword()).trim();
        String rolSeleccionado = cmbRol.getSelectedItem().toString();

        if (nombre.isEmpty() || apellido.isEmpty() || dui.isEmpty() || telefono.isEmpty() || correo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los datos personales son obligatorios.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!dui.matches("^\\d{8}-\\d{1}$") || !telefono.matches("^\\d{8}$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El formato de DUI (00000000-0) o Teléfono (8 dígitos) es inválido.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        Usuario u = new Usuario();
        u.setIdUsuario(idSeleccionado);
        u.setNombre(nombre);
        u.setApellido(apellido);
        u.setDui(dui);
        u.setTelefono(telefono);
        u.setCorreo(correo);
        u.setRol(rolSeleccionado.equals("Administrador") ? 1 : 2);

        boolean actualizarClave = !clavePlana.isEmpty();
        if (actualizarClave) {
            u.setClave(Seguridad.encriptarSHA256(clavePlana));
        }

        UsuarioDAO dao = new UsuarioDAO();
        if (dao.actualizarUsuario(u, actualizarClave)) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario actualizado correctamente!");
            btnLimpiar.doClick();
            Usuario usuarioVacio = new Usuario(); // Crea un usuario con todos los strings nulos/vacios
            cargarTabla(usuarioVacio);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al actualizar el usuario.", "Error de BD", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // 1. Armamos un "Usuario molde" con lo que haya en las cajas de texto
        Usuario moldeBusqueda = new Usuario();
        moldeBusqueda.setNombre(txtNombre.getText().trim());
        moldeBusqueda.setApellido(txtApellido.getText().trim());
        moldeBusqueda.setDui(txtDui.getText().trim());
        moldeBusqueda.setTelefono(txtTelefono.getText().trim());
        moldeBusqueda.setCorreo(txtCorreo.getText().trim());
        moldeBusqueda.setNombreUsuario(txtUsuario.getText().trim());

        // 2. Capturamos el rol seleccionado en el ComboBox
        String rolSeleccionado = cmbRol.getSelectedItem().toString();
        int idRol = rolSeleccionado.equals("Administrador") ? 1 : 2;
        moldeBusqueda.setRol(idRol);

        // 3. Enviamos el molde al método de la tabla
        cargarTabla(moldeBusqueda);
        
        // 4. Le avisamos al usuario si la búsqueda no dio resultados
        if (tblUsuarios.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron usuarios con esos criterios.", "Búsqueda", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDui;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables






// Método que recibe un "Usuario molde" para filtrar la tabla
    private void cargarTabla(Usuario filtro) {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Usuario");
        modelo.addColumn("DUI");
        modelo.addColumn("Correo");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Rol");
        
        tblUsuarios.setModel(modelo);

        UsuarioDAO dao = new UsuarioDAO();
        java.util.List<Usuario> listaUsuarios = dao.buscarUsuariosAvanzado(filtro);

        String[] fila = new String[8];
        for (Usuario u : listaUsuarios) {
            fila[0] = String.valueOf(u.getIdUsuario());
            fila[1] = u.getNombre();
            fila[2] = u.getApellido();
            fila[3] = u.getNombreUsuario();
            fila[4] = u.getDui();
            fila[5] = u.getCorreo();
            fila[6] = u.getTelefono();
            fila[7] = (u.getRol() == 1) ? "Administrador" : "Vendedor";
            
            modelo.addRow(fila);
        }
    }



}
