/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.giv.pesados.vistas;

import com.mycompany.giv.pesados.config.Conexion;
import com.mycompany.giv.pesados.config.Seguridad;

/**
 *
 * @author willi
 */
public class FrmUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmUsuarios
     */
    
    // Variable para guardar el ID del usuario al que le demos clic en la tabla
    private int idSeleccionado = 0;
    
    
    public FrmUsuarios() {
        initComponents();
        
        // Cargar el logo por código desde la carpeta resources de Maven
        try {
            java.net.URL urlLogo = getClass().getResource("/GIV-PESADOS.png");
            
            if (urlLogo != null) {
                javax.swing.ImageIcon iconoLogo = new javax.swing.ImageIcon(urlLogo);
                
                // Le damos un tamaño fijo de 200 de ancho por 100 de alto (podés cambiar estos números a tu gusto)
                java.awt.Image imgEscalada = iconoLogo.getImage().getScaledInstance(250, 250, java.awt.Image.SCALE_SMOOTH);
                
                lblLogo.setIcon(new javax.swing.ImageIcon(imgEscalada));
            }
        } catch (Exception e) {
            System.out.println("Error cargando el logo: " + e.getMessage());
        }

        
        cargarTabla();
        
        
// === CARGAR ÍCONOS DE BOTONES POR CÓDIGO (CON AJUSTE DE TAMAÑO) ===
        try {
            // 1. Ícono Guardar
            javax.swing.ImageIcon icoGuardar = new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"));
            java.awt.Image imgGuardar = icoGuardar.getImage().getScaledInstance(64, 64, java.awt.Image.SCALE_SMOOTH);
            btnGuardar.setIcon(new javax.swing.ImageIcon(imgGuardar));
            
            // 2. Ícono Actualizar
            javax.swing.ImageIcon icoEditar = new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"));
            java.awt.Image imgEditar = icoEditar.getImage().getScaledInstance(64, 64, java.awt.Image.SCALE_SMOOTH);
            btnActualizar.setIcon(new javax.swing.ImageIcon(imgEditar));
            
            // 3. Ícono Eliminar
            javax.swing.ImageIcon icoEliminar = new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"));
            java.awt.Image imgEliminar = icoEliminar.getImage().getScaledInstance(64, 64, java.awt.Image.SCALE_SMOOTH);
            btnEliminar.setIcon(new javax.swing.ImageIcon(imgEliminar));
            
            // 4. Ícono Limpiar
            javax.swing.ImageIcon icoLimpiar = new javax.swing.ImageIcon(getClass().getResource("/img/limpiar.png"));
            java.awt.Image imgLimpiar = icoLimpiar.getImage().getScaledInstance(64, 64, java.awt.Image.SCALE_SMOOTH);
            btnLimpiar.setIcon(new javax.swing.ImageIcon(imgLimpiar));

        } catch (Exception e) {
            System.out.println("Error cargando íconos de botones: " + e.getMessage());
        }
        
        
        
        // === ESTILO DE LA TABLA (DISEÑO HTML) ===
        // 1. Diseño del encabezado (Azul Marino con letras blancas)
        tblUsuarios.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        tblUsuarios.getTableHeader().setOpaque(false);
        tblUsuarios.getTableHeader().setBackground(new java.awt.Color(0, 52, 89));
        tblUsuarios.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        
        // 2. Diseño de las filas (Letra Segoe UI y filas más altas)
        tblUsuarios.setRowHeight(30); 
        tblUsuarios.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        
        // 3. Color al hacer clic en una fila (Azul Celeste)
        tblUsuarios.setSelectionBackground(new java.awt.Color(0, 180, 216));
        tblUsuarios.setSelectionForeground(java.awt.Color.WHITE);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDui = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(248, 249, 250));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblTitulo.setText("REGISTRO DE USUARIOS");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre:");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Apellido:");

        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("DUI:");

        txtDui.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Teléfono:");

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Correo Electrónico:");

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Nombre de Usuario:");

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Contraseña:");

        txtClave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Rol de Acceso:");

        cmbRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedor" }));

        btnGuardar.setBackground(new java.awt.Color(42, 157, 143));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFocusPainted(false);
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnActualizar.setBackground(new java.awt.Color(0, 180, 216));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setBorderPainted(false);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setFocusPainted(false);
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(230, 57, 70));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        btnLimpiar.setBackground(new java.awt.Color(0, 52, 89));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.setContentAreaFilled(false);
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.setFocusPainted(false);
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario)
                            .addComponent(txtClave)
                            .addComponent(txtDui)
                            .addComponent(txtTelefono)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCorreo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)))
                .addGap(265, 265, 265))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(lblTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(457, 457, 457)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
// 1. EXTRAER TODOS LOS DATOS
        String nombre = txtNombre.getText().trim(); // El trim() elimina espacios al inicio y final
        String apellido = txtApellido.getText().trim();
        String dui = txtDui.getText().trim();
        String telefono = txtTelefono.getText().trim();
        String correo = txtCorreo.getText().trim();
        String usuario = txtUsuario.getText().trim();
        String clavePlana = new String(txtClave.getPassword()).trim();
        String rolSeleccionado = cmbRol.getSelectedItem().toString();

        // 2. VALIDACIÓN NIVEL 1: CAMPOS VACÍOS
        if (nombre.isEmpty() || apellido.isEmpty() || dui.isEmpty() || 
            telefono.isEmpty() || correo.isEmpty() || usuario.isEmpty() || clavePlana.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Todos los campos son obligatorios. No se permiten campos vacíos.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Detener ejecución
        }

        // 3. VALIDACIÓN NIVEL 2: FORMATOS CORRECTOS (Expresiones Regulares)
        // Validar que nombre y apellido solo tengan letras (y espacios entre nombres)
        if (!nombre.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$") || !apellido.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: El nombre y apellido solo pueden contener letras.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar formato del DUI (8 números, guion, 1 número)
        if (!dui.matches("^\\d{8}-\\d{1}$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: El formato del DUI debe ser 00000000-0.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar correo (que tenga @ y un punto)
        if (!correo.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingrese un correo electrónico válido.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 4. PREPARAR DATOS FINALES
        // Convertir el texto del ComboBox al número que espera la Base de Datos
        int idRol = rolSeleccionado.equals("Administrador") ? 1 : 2;
        // Encriptar la contraseña usando tu clase de seguridad
        String claveEncriptada = Seguridad.encriptarSHA256(clavePlana);

        // 5. ENVIAR A LA BASE DE DATOS (Google Cloud)
        try {
            java.sql.Connection cn = Conexion.getInstancia().conectar();
            
            // Primero, verificar que el nombre_usuario no exista ya (Validación de duplicados)
            String sqlCheck = "SELECT nombre_usuario FROM USUARIOS WHERE nombre_usuario = ?";
            java.sql.PreparedStatement pstCheck = cn.prepareStatement(sqlCheck);
            pstCheck.setString(1, usuario);
            java.sql.ResultSet rs = pstCheck.executeQuery();
            
            if (rs.next()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: El nombre de usuario '" + usuario + "' ya existe. Elija otro.", "Duplicado", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Si pasa todas las pruebas, Insertar
            String sqlInsert = "INSERT INTO USUARIOS (nombre, apellido, nombre_usuario, DUI, correo, telefono, estado, clave, rol) VALUES (?, ?, ?, ?, ?, ?, 1, ?, ?)";
            java.sql.PreparedStatement pst = cn.prepareStatement(sqlInsert);
            
            pst.setString(1, nombre);
            pst.setString(2, apellido);
            pst.setString(3, usuario);
            pst.setString(4, dui);
            pst.setString(5, correo);
            pst.setString(6, telefono);
            pst.setString(7, claveEncriptada);
            pst.setInt(8, idRol);

            pst.executeUpdate(); // Ejecutar guardado
            
            javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario Registrado Exitosamente en la Nube!");
            
            
            
            // 1. Volver a consultar la nube para refrescar la tabla
            cargarTabla();
            
            // 2. Hacer un clic "fantasma" en el botón limpiar para vaciar las cajitas
            btnLimpiar.doClick();
            
            
            // TODO: Aquí llamaremos al método para limpiar las cajas de texto y actualizar la tabla
            
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error de Base de Datos: " + e.getMessage(), "Error Crítico", javax.swing.JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        
// 1. Averiguar a qué fila se le dio clic
        int filaSeleccionada = tblUsuarios.getSelectedRow();

        if (filaSeleccionada >= 0) {
            // 2. Guardar el ID de la columna 0 en nuestra variable secreta
            idSeleccionado = Integer.parseInt(tblUsuarios.getValueAt(filaSeleccionada, 0).toString());

            // 3. Subir los datos a las cajitas respetando el nuevo orden
            txtNombre.setText(tblUsuarios.getValueAt(filaSeleccionada, 1).toString());
            txtApellido.setText(tblUsuarios.getValueAt(filaSeleccionada, 2).toString());
            txtUsuario.setText(tblUsuarios.getValueAt(filaSeleccionada, 3).toString());
            txtDui.setText(tblUsuarios.getValueAt(filaSeleccionada, 4).toString());
            txtCorreo.setText(tblUsuarios.getValueAt(filaSeleccionada, 5).toString());   // <--- CORREO ARREGLADO
            txtTelefono.setText(tblUsuarios.getValueAt(filaSeleccionada, 6).toString()); // <--- TELÉFONO ARREGLADO
            
            // Seleccionar el rol correcto en la lista desplegable (ahora pasó a la columna 7)
            String rol = tblUsuarios.getValueAt(filaSeleccionada, 7).toString();
            cmbRol.setSelectedItem(rol);
            
            // La contraseña la dejamos vacía por seguridad
            txtClave.setText("");
            
            // Blindaje 100%: Bloqueamos la edición para que no cambien el "username"
            txtUsuario.setEditable(false);
        }
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
txtUsuario.setEditable(true);
// Vaciar todas las cajitas
        txtNombre.setText("");
        txtApellido.setText("");
        txtDui.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtUsuario.setText("");
        txtClave.setText("");
        cmbRol.setSelectedIndex(0); 
        
        // Desbloquear la caja de usuario por si queremos guardar uno nuevo
        txtUsuario.setEnabled(true);
        
        // Resetear el ID
        idSeleccionado = 0;

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        

// 1. Validar que se haya seleccionado un usuario en la tabla
        if (idSeleccionado == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un usuario de la tabla primero.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Extraer datos (El usuario no se extrae porque no se puede cambiar)
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String dui = txtDui.getText().trim();
        String telefono = txtTelefono.getText().trim();
        String correo = txtCorreo.getText().trim();
        String clavePlana = new String(txtClave.getPassword()).trim();
        int idRol = cmbRol.getSelectedItem().toString().equals("Administrador") ? 1 : 2;

        // 3. Validaciones de campos vacíos y formatos
        if (nombre.isEmpty() || apellido.isEmpty() || dui.isEmpty() || telefono.isEmpty() || correo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los datos personales son obligatorios.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!dui.matches("^\\d{8}-\\d{1}$")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El formato del DUI debe ser 00000000-0.", "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 4. Actualizar en Google Cloud
        try {
            java.sql.Connection cn = Conexion.getInstancia().conectar();
            java.sql.PreparedStatement pst;

            // Lógica: ¿Escribió una nueva contraseña o la dejó en blanco?
            if (clavePlana.isEmpty()) {
                // Actualizar todo MENOS la contraseña
                String sql = "UPDATE USUARIOS SET nombre=?, apellido=?, DUI=?, telefono=?, correo=?, rol=? WHERE id_usuario=?";
                pst = cn.prepareStatement(sql);
                pst.setString(1, nombre);
                pst.setString(2, apellido);
                pst.setString(3, dui);
                pst.setString(4, telefono);
                pst.setString(5, correo);
                pst.setInt(6, idRol);
                pst.setInt(7, idSeleccionado);
            } else {
                // Encriptar la nueva y actualizar TODO
                String claveEncriptada = Seguridad.encriptarSHA256(clavePlana);
                String sql = "UPDATE USUARIOS SET nombre=?, apellido=?, DUI=?, telefono=?, correo=?, rol=?, clave=? WHERE id_usuario=?";
                pst = cn.prepareStatement(sql);
                pst.setString(1, nombre);
                pst.setString(2, apellido);
                pst.setString(3, dui);
                pst.setString(4, telefono);
                pst.setString(5, correo);
                pst.setInt(6, idRol);
                pst.setString(7, claveEncriptada);
                pst.setInt(8, idSeleccionado);
            }

            pst.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario actualizado correctamente!");
            
            // Refrescar la tabla para ver los cambios
            cargarTabla();
            
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }


// TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed


// 1. Validar que haya seleccionado a alguien en la tabla
        if (idSeleccionado == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione el usuario que desea eliminar.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Pedir confirmación (¡Nunca se elimina sin preguntar!)
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
                "¿Está seguro que desea dar de baja a este usuario? Ya no podrá acceder al sistema.", 
                "Confirmar Eliminación", 
                javax.swing.JOptionPane.YES_NO_OPTION, 
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        // Si el usuario presiona "Sí" (que equivale a 0)
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            try {
                java.sql.Connection cn = Conexion.getInstancia().conectar();
                
                // 3. Hacer el Borrado Lógico (Cambiar estado a 0)
                String sql = "UPDATE USUARIOS SET estado = 0 WHERE id_usuario = ?";
                java.sql.PreparedStatement pst = cn.prepareStatement(sql);
                pst.setInt(1, idSeleccionado);
                
                pst.executeUpdate();
                
                javax.swing.JOptionPane.showMessageDialog(this, "Usuario dado de baja exitosamente.");
                
                // 4. Limpiar las cajas y refrescar la tabla para que desaparezca
                btnLimpiar.doClick(); // Esto simula un clic en tu botón limpiar
                cargarTabla();
                
            } catch (java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDui;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables






// Método para mostrar los usuarios en la tabla
        private void cargarTabla() {
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("ID");          // Columna 0
        modelo.addColumn("Nombre");      // Columna 1
        modelo.addColumn("Apellido");    // Columna 2
        modelo.addColumn("Usuario");     // Columna 3
        modelo.addColumn("DUI");         // Columna 4
        modelo.addColumn("Correo");      // Columna 5
        modelo.addColumn("Teléfono");    // Columna 6
        modelo.addColumn("Rol");         // Columna 7
        
        tblUsuarios.setModel(modelo);

        try {
            java.sql.Connection cn = Conexion.getInstancia().conectar();
            // Agregamos correo y telefono a la consulta SQL
            String sql = "SELECT id_usuario, nombre, apellido, nombre_usuario, DUI, correo, telefono, rol FROM USUARIOS WHERE estado = 1";
            java.sql.Statement st = cn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);

            String[] fila = new String[8]; // Ahora son 8 campos
            while (rs.next()) {
                fila[0] = rs.getString("id_usuario");
                fila[1] = rs.getString("nombre");
                fila[2] = rs.getString("apellido");
                fila[3] = rs.getString("nombre_usuario");
                fila[4] = rs.getString("DUI");
                fila[5] = rs.getString("correo");    // <--- Traemos correo
                fila[6] = rs.getString("telefono");  // <--- Traemos teléfono
                
                int rolDB = rs.getInt("rol");
                fila[7] = (rolDB == 1) ? "Administrador" : "Vendedor";
                
                modelo.addRow(fila);
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar la tabla: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }



}
