/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.giv.pesados.vistas;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author bryan
 */
public class FrmVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmVentas
     */
    private int rolUsuario;
    // Variable global para capturar el ID que nos manda el catálogo
    private int idProductoTemp = 0; 
    // Variable para guardar el ID del cliente que hará la compra
    private int idClienteTemp = 0;
    
    
    // Modelo de la tabla (el carrito en memoria)
    private DefaultTableModel modeloVenta = new DefaultTableModel();
    
    public FrmVentas(int rol) {
        initComponents();
        this.rolUsuario = rol;
        // Configuramos las 6 columnas exactas para DETALLE_VENTAS [cite: 99-103]
        modeloVenta.addColumn("ID Producto");
        modeloVenta.addColumn("Nombre Repuesto");
        modeloVenta.addColumn("Cantidad");
        modeloVenta.addColumn("Precio U.");
        modeloVenta.addColumn("Descuento");
        modeloVenta.addColumn("Subtotal");
        
        TbDetalleVenta.setModel(modeloVenta);
    }
    
    public void calcularTotalPagar() {
        double total = 0.00;
        int numFilas = TbDetalleVenta.getRowCount();

        for (int i = 0; i < numFilas; i++) {
            // El subtotal está en la columna 5 (índice 5)
            double subtotalFila = Double.parseDouble(TbDetalleVenta.getValueAt(i, 5).toString());
            total += subtotalFila;
        }
        
        // Actualizamos tu JTextField del total (asumo que lo llamaste TxtTotalPagar)
        // Usa tu nombre de variable real aquí
        TxtTotalPagar.setText(String.format("%.2f", total)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        CbTipoComprobante = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        TxtDuiCliente = new javax.swing.JTextField();
        TxtNombreCliente = new javax.swing.JTextField();
        BtnBuscarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CbMetodoPago = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BtnBuscarModal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TxtNombreProducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtStock = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TxtPrecioUnitario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtCantidad = new javax.swing.JTextField();
        BtnAgregarCarrito = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbDetalleVenta = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TxtTotalPagar = new javax.swing.JTextField();
        BtnGenerarVenta = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        CbTipoComprobante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ticket", "Factura Consumidor Final ", "Comprobante de Crédito Fiscal" }));

        jLabel4.setText("Tipo de Comprobante:");

        TxtNombreCliente.setEditable(false);

        BtnBuscarCliente.setText("Buscar");
        BtnBuscarCliente.addActionListener(this::BtnBuscarClienteActionPerformed);

        jLabel2.setText("Numero de DUI:");

        jLabel3.setText("Nombre Cliente:");

        jLabel5.setText("Metodo de Pago:");

        CbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo ", "Tarjeta", " " }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Datos de la Venta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(CbTipoComprobante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(90, 90, 90)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(280, 280, 280))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(46, 46, 46)
                                .addComponent(CbMetodoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtDuiCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnBuscarCliente)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtDuiCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CbTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Area de Venta");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Buscador de Repuestos");

        BtnBuscarModal.setText("Abrir Catalogo de Repuestos");
        BtnBuscarModal.addActionListener(this::BtnBuscarModalActionPerformed);

        jLabel7.setText("Nombre Producto:");

        TxtNombreProducto.setEditable(false);

        jLabel9.setText("Stock:");

        TxtStock.setEditable(false);

        jLabel10.setText("Precio Unitario:");

        TxtPrecioUnitario.setEditable(false);

        jLabel11.setText("Cantidad a Agregar:");

        BtnAgregarCarrito.setText("Agregar al Carrito");
        BtnAgregarCarrito.addActionListener(this::BtnAgregarCarritoActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TxtCantidad)
                            .addComponent(TxtNombreProducto)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBuscarModal, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAgregarCarrito)
                .addGap(152, 152, 152))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(BtnBuscarModal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(TxtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAgregarCarrito)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        TbDetalleVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TbDetalleVenta);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("Detalle de Venta");

        jLabel13.setText("Total a Pagar:");

        TxtTotalPagar.setEditable(false);

        BtnGenerarVenta.setText("Generar Venta");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(381, 381, 381))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(BtnGenerarVenta))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TxtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnGenerarVenta))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(368, 368, 368))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarClienteActionPerformed
        // TODO add your handling code here:
        // 1. Capturamos el DUI escrito y quitamos espacios en blanco
        String dui = TxtDuiCliente.getText().trim();

        // 2. Validamos que no esté vacío
        if (dui.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Por favor ingrese el número de DUI para buscar.");
            return;
        }

        // 3. Instanciamos el DAO y usamos el método de búsqueda que ya creaste
        com.mycompany.giv.pesados.dao.ClienteDAO clienteDao = new com.mycompany.giv.pesados.dao.ClienteDAO();
        
        // Pasamos el DUI y el rol (asumiendo que tu FrmVentas ya tiene this.rolUsuario)
        java.util.List<com.mycompany.giv.pesados.modelos.Cliente> lista = clienteDao.buscarClientes(dui, this.rolUsuario);

        // 4. Evaluamos si encontró al cliente
        if (!lista.isEmpty()) {
            // Como buscamos por un DUI específico, agarramos el primer resultado de la lista
            com.mycompany.giv.pesados.modelos.Cliente cl = lista.get(0);
            
            // Mostramos el nombre en la caja de texto (recuerda ponerla como NO editable)
            TxtNombreCliente.setText(cl.getNombreCliente());
            
            // ¡CRUCIAL! Guardamos el ID del cliente para cuando le demos al botón "Procesar Venta"
            idClienteTemp = cl.getIdCliente(); 
            
        } else {
            // Si no hay resultados (o si el cliente está inactivo y es vendedor)
            javax.swing.JOptionPane.showMessageDialog(null, "Cliente no encontrado o inactivo. Verifique el DUI.");
            TxtNombreCliente.setText("");
            idClienteTemp = 0;
        }
    }//GEN-LAST:event_BtnBuscarClienteActionPerformed

    private void BtnBuscarModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarModalActionPerformed
        // TODO add your handling code here:
        // 1. Abrimos el catálogo bloqueando el fondo (modal = true)
        DlgBuscarProducto modal = new DlgBuscarProducto(new javax.swing.JFrame(), true);
        modal.setLocationRelativeTo(null); // Centrar en pantalla
        modal.setVisible(true); // El código de FrmVentas se pausa aquí hasta que cierres el catálogo

        // 2. Cuando el vendedor haga doble clic en un repuesto, la ventana se cerrará y el código continuará aquí
        if (modal.idSeleccionado > 0) {
            // Asignamos los valores a los JTextFields de tu FrmVentas
            TxtNombreProducto.setText(modal.nombreSeleccionado);
            
            // Al ser un JTextField, es mejor pasar solo el número limpio como texto
            TxtStock.setText(String.valueOf(modal.stockSeleccionado)); 
            TxtPrecioUnitario.setText(String.valueOf(modal.precioSeleccionado));

            // CRUCIAL: Guardamos el ID del producto en la variable global para el botón Agregar al Carrito
            idProductoTemp = modal.idSeleccionado;

            // Mandamos el cursor a la caja de cantidad para que el vendedor escriba rápido
            TxtCantidad.requestFocus();
        }
    }//GEN-LAST:event_BtnBuscarModalActionPerformed

    private void BtnAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarCarritoActionPerformed
        // TODO add your handling code here:
        // 1. Validamos que haya un producto seleccionado y cantidad ingresada
        if (idProductoTemp == 0 || TxtCantidad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe buscar un producto y especificar la cantidad a vender.");
            return;
        }

        try {
            int cantidad = Integer.parseInt(TxtCantidad.getText());
            int stockDisponible = Integer.parseInt(TxtStock.getText());
            double precio = Double.parseDouble(TxtPrecioUnitario.getText());
            
            // Asumimos 0 si el campo de descuento no existe o está vacío
            double descuento = 0.0; 
            
            // 2. Validación de Stock [cite: 17, 34]
            if (cantidad > stockDisponible) {
                JOptionPane.showMessageDialog(null, "Stock insuficiente. Solo hay " + stockDisponible + " unidades disponibles.");
                return;
            }
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(null, "La cantidad debe ser mayor a cero.");
                return;
            }

            // 3. Calculamos el subtotal de esta línea
            double subtotal = (cantidad * precio) - descuento;

            // 4. Preparamos la fila y la agregamos al JTable (Carrito)
            Object[] fila = new Object[6];
            fila[0] = idProductoTemp;
            fila[1] = TxtNombreProducto.getText();
            fila[2] = cantidad;
            fila[3] = precio;
            fila[4] = descuento;
            fila[5] = subtotal;

            modeloVenta.addRow(fila);

            // 5. Limpiamos los campos para el siguiente producto
            idProductoTemp = 0;
            TxtNombreProducto.setText("");
            TxtStock.setText("");
            TxtPrecioUnitario.setText("");
            TxtCantidad.setText("");
            
            // 6. Ejecutamos el cálculo matemático para actualizar el Total a Pagar
            calcularTotalPagar();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: Ingrese valores numéricos válidos en Cantidad y Precio.");
        }
    }//GEN-LAST:event_BtnAgregarCarritoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarCarrito;
    private javax.swing.JButton BtnBuscarCliente;
    private javax.swing.JButton BtnBuscarModal;
    private javax.swing.JButton BtnGenerarVenta;
    private javax.swing.JComboBox<String> CbMetodoPago;
    private javax.swing.JComboBox<String> CbTipoComprobante;
    private javax.swing.JTable TbDetalleVenta;
    private javax.swing.JTextField TxtCantidad;
    private javax.swing.JTextField TxtDuiCliente;
    private javax.swing.JTextField TxtNombreCliente;
    private javax.swing.JTextField TxtNombreProducto;
    private javax.swing.JTextField TxtPrecioUnitario;
    private javax.swing.JTextField TxtStock;
    private javax.swing.JTextField TxtTotalPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
